### ISSUE TITLE
own_piece? should only return un-captured pieces

### ISSUE THREAD

**Issue by addstar34** [teamendgame/endgame-chess#37]
The own_piece? method is returning all pieces for the particular player regardless if they are captured or not.
This needs to only return pieces where captured is false.

**Comment by jonathanpike** [comment]
While you're right in terms of manually writing tests, if you take a look at @takehiromouri's `move_to!` method in the [Castling PR at line 9](https://github.com/teamendgame/endgame-chess/pull/33/files#diff-5107f37eb1951c4fdb7459f6212467d2R9), you can see that when a piece is captured, its `row_position` and `col_position` are updated to `nil`.  Since `own_piece?` is looking for pieces at a particular row or column, it wouldn't find these pieces.

**Comment by addstar34** [comment]
As per our hangout @takehiromouri's move_to! method removes captured pieces from the board so this is a non issue. To keep things consistent with not needing to check captured it appears only the obstructed? method is checking captured: false but this isn't necessary so I will raise another issue to refactor the obstructed? method.
